function str_text = CleanString(str_text)

str_text = lower(str_text);
str_text = strrep(str_text,'-lrb-','');
str_text = strrep(str_text,'-rrb-','');
str_text = strrep(str_text,char(255),' ');
str_text = strrep(str_text,char(231),'c'); % ç -> c
str_text = strrep(str_text,char(232),'e'); % è -> e
str_text = strrep(str_text,char(236),'i'); % ì -> i
str_text = strrep(str_text,' %','%');
str_text = strrep(str_text,',','');
str_text = strrep(str_text,'-',' ');
str_text = strrep(str_text,';','');
str_text = strrep(str_text,'"','');
str_text = strrep(str_text,' ` ','');
str_text = strrep(str_text,'`','');
str_text = strrep(str_text,'\','');
str_text = strrep(str_text,'/','');
str_text = strrep(str_text,':','');
str_text = strrep(str_text,' ''','');
str_text = strrep(str_text,'''','');
str_text = strrep(str_text,'[','');
str_text = strrep(str_text,']','');
str_text = strrep(str_text,'(','');
str_text = strrep(str_text,')','');
str_text = strrep(str_text,'organisation','organization');
str_text = strrep(str_text,'grey','gray');
str_text = regexprep(str_text,'([0-9])([a-z])','$1 $2');
str_text = regexprep(strtrim(str_text),'\s+',' ');
