function [F,J] = costFunctionCameraResectioning_v02(params,X,x)
% Cost function for camera resectioning using geometric error.

if size(X,1) < 4
  X = [X; ones(1,size(X,2))];
end

f = params(1); px = params(2); py = params(3);
wx = params(4); wy = params(5); wz = params(6);
cx = params(7); cy = params(8); cz = params(9);

% Rotation matrix:
t = sqrt(wx^2+wy^2+wz^2)+eps;
nx = wx/t;
ny = wy/t;
nz = wz/t;
N = [0 -nz ny; nz 0 -nx; -ny nx 0];
R = eye(3) + sin(t)*N + (1-cos(t))*N*N;

% Camera center:
C = [cx; cy; cz];

% Calibration matrix:
K = [f 0 px; 0 f py; 0 0 1];

% Camera matrix:
P = K*R*[eye(3) -C];

% Project 3D points to 2D:
xx = P*X; ww = xx(3,:); yy = xx(2,:); xx = xx(1,:);

% Compute cost:
F = [xx./ww-x(1,:) yy./ww-x(2,:)]';

if nargout >= 2
  % Compute derivative information:
  [Gx,Gy] = GetDerivs(X(1,:),X(2,:),X(3,:),cx,cy,cz,f,px,py,wx,wy,wz,xx,yy,ww);

  J = [Gx Gy]';
  
  % TO DO: Add regularization...

end

return;


function [Gx,Gy] = GetDerivs(Xi,Yi,Zi,cx,cy,cz,f,px,py,wx,wy,wz,xx,yy,ww)
%OUT_DERIVE
%    [GX,GY] = OUT_DERIVE(EPS,XI,YI,ZI,CX,CY,CZ,F,PX,PY,WW,WX,WY,WZ,XX,YY)

%    This function was generated by the Symbolic Math Toolbox version 5.2.
%    10-Nov-2012 14:57:20

N = length(Xi);
EPS = eps;

t2 = wy.^2;
t3 = wx.^2;
t4 = wz.^2;
t5 = t2 + t3 + t4;
t6 = t5.^(1./2);
t7 = EPS + t6;
t8 = cos(t7);
t9 = t8 - 1;
t10 = 1./t7.^2;
t11 = t10.*t2.*t9;
t12 = t10.*t4.*t9;
t13 = t11 + t12 + 1;
t14 = sin(t7);
t15 = 1./t7;
t16 = t14.*t15.*wz;
t17 = t10.*t9.*wx.*wy;
t18 = t16 + t17;
t19 = t14.*t15.*wy;
t24 = t10.*t9.*wx.*wz;
t20 = t19 - t24;
t21 = 1./ww;
t22 = t10.*t3.*t9;
t23 = t11 + t22 + 1;
t25 = t19 + t24;
t26 = t14.*t15.*wx;
t107 = t10.*t9.*wy.*wz;
t27 = t26 - t107;
t28 = 1./t5.^(1./2);
t29 = t10.*t14.*t28.*wx.*wy;
t30 = t10.*t14.*t28.*t3.*wz;
t31 = 1./t7.^3;
t32 = 2.*t28.*t3.*t31.*t9.*wz;
t44 = t10.*t9.*wz;
t45 = t15.*t28.*t8.*wx.*wy;
t33 = t29 + t30 + t32 - t44 - t45;
t34 = t10.*t14.*t28.*t3.*wx;
t35 = 2.*t28.*t3.*t31.*t9.*wx;
t36 = t10.*t14.*t2.*t28.*wx;
t37 = 2.*t2.*t28.*t31.*t9.*wx;
t46 = 2.*t10.*t9.*wx;
t38 = t34 + t35 + t36 + t37 - t46;
t39 = t14.*t15;
t40 = t15.*t28.*t3.*t8;
t41 = t10.*t14.*t28.*wx.*wy.*wz;
t42 = 2.*t28.*t31.*t9.*wx.*wy.*wz;
t47 = t10.*t14.*t28.*t3;
t43 = t39 + t40 + t41 + t42 - t47;
t48 = t30 - t29 + t32 - t44 + t45;
t49 = f.*t48;
t50 = t49 - px.*t38;
t51 = px.*t43;
t52 = t10.*t14.*t28.*wx.*wz;
t53 = t10.*t14.*t28.*t3.*wy;
t54 = 2.*t28.*t3.*t31.*t9.*wy;
t90 = t10.*t9.*wy;
t91 = t15.*t28.*t8.*wx.*wz;
t55 = t52 + t53 + t54 - t90 - t91;
t56 = f.*t55;
t57 = t51 + t56;
t58 = t10.*t14.*t28.*t4.*wx;
t59 = 2.*t28.*t31.*t4.*t9.*wx;
t60 = t36 + t37 + t58 + t59;
t61 = f.*t60;
t62 = t61 - px.*t33;
t63 = 1./ww.^2;
t64 = t10.*t14.*t2.*t28.*wz;
t65 = 2.*t2.*t28.*t31.*t9.*wz;
t66 = t45 - t44 - t29 + t64 + t65;
t67 = t10.*t14.*t2.*t28.*wy;
t68 = 2.*t2.*t28.*t31.*t9.*wy;
t73 = 2.*t10.*t9.*wy;
t69 = t53 + t54 + t67 + t68 - t73;
t70 = t10.*t14.*t2.*t28;
t72 = t15.*t2.*t28.*t8;
t71 = t41 - t39 + t42 + t70 - t72;
t74 = t39 + t41 + t42 - t70 + t72;
t75 = f.*t74;
t76 = t75 - px.*t69;
t77 = t10.*t14.*t28.*t4.*wy;
t78 = 2.*t28.*t31.*t4.*t9.*wy;
t79 = t67 + t68 - t73 + t77 + t78;
t80 = f.*t79;
t81 = t10.*t14.*t28.*wy.*wz;
t88 = t10.*t9.*wx;
t89 = t15.*t28.*t8.*wy.*wz;
t82 = t36 + t37 + t81 - t88 - t89;
t83 = f.*t82;
t84 = px.*t66;
t85 = t83 + t84;
t86 = t80 - px.*t71;
t87 = t30 + t32 + t64 + t65;
t92 = t58 + t59 + t81 - t88 - t89;
t93 = t77 - t52 + t78 - t90 + t91;
t94 = t10.*t14.*t28.*t4.*wz;
t95 = 2.*t28.*t31.*t4.*t9.*wz;
t147 = 2.*t10.*t9.*wz;
t96 = t64 - t147 + t65 + t94 + t95;
t97 = f.*t96;
t98 = px.*t93;
t99 = t10.*t14.*t28.*t4;
t148 = t15.*t28.*t4.*t8;
t100 = t41 - t39 - t148 + t42 + t99;
t101 = f.*t100;
t102 = t101 + t98;
t103 = t58 + t59 - t81 - t88 + t89;
t104 = f.*t103;
t105 = t104 - px.*t87;
t106 = t97 - px.*t92;
t108 = t12 + t22 + 1;
t109 = t16 - t17;
t110 = t107 + t26;
t111 = cz.*t23;
t112 = Xi.*t25;
t113 = cy.*t27;
t114 = t111 + t112 + t113 - Yi.*t27 - Zi.*t23 - cx.*t25;
t115 = Xi.*t33;
t116 = Yi.*t43;
t117 = cz.*t38;
t118 = t115 + t116 + t117 - Zi.*t38 - cx.*t33 - cy.*t43;
t119 = t41 - t40 - t39 + t42 + t47;
t120 = f.*t119;
t121 = t120 - py.*t38;
t122 = py.*t43;
t123 = t34 + t35 - t46 + t58 + t59;
t124 = t122 - f.*t123;
t125 = t53 - t52 + t54 - t90 + t91;
t126 = f.*t125;
t127 = py.*t33;
t128 = t126 + t127;
t129 = Yi.*t66;
t130 = Xi.*t71;
t131 = cz.*t69;
t132 = t129 + t130 + t131 - Zi.*t69 - cx.*t71 - cy.*t66;
t133 = t29 - t44 - t45 + t64 + t65;
t134 = f.*t133;
t135 = t134 - py.*t69;
t136 = py.*t71;
t137 = t36 + t37 - t81 - t88 + t89;
t138 = f.*t137;
t139 = t136 + t138;
t140 = t53 + t54 + t77 + t78;
t141 = f.*t140;
t142 = t141 - py.*t66;
t143 = cz.*t87;
t144 = Xi.*t92;
t145 = Yi.*t93;
t146 = t143 + t144 + t145 - Zi.*t87 - cx.*t92 - cy.*t93;
t149 = py.*t93;
t150 = t30 - t147 + t32 + t94 + t95;
t151 = t149 - f.*t150;
t152 = py.*t92;
t153 = t148 + t39 + t41 + t42 - t99;
t154 = f.*t153;
t155 = t152 + t154;
t156 = t52 + t77 + t78 - t90 - t91;
t157 = f.*t156;
t158 = t157 - py.*t87;

Gx = [t21.*(Xi.*t13 - Yi.*t18 + Zi.*t20 - cx.*t13 + cy.*t18 - cz.*t20);-t114.*t21;zeros(1,N);-t63.*(t118.*xx + ww.*(Xi.*t62 - Yi.*t57 - Zi.*t50 - cx.*t62 + cy.*t57 + cz.*t50));-t63.*(t132.*xx + ww.*(Xi.*t86 - Yi.*t85 - Zi.*t76 - cx.*t86 + cy.*t85 + cz.*t76));-t63.*(t146.*xx + ww.*(Xi.*t106 - Yi.*t102 - Zi.*t105 - cx.*t106 + cy.*t102 + cz.*t105));-t63.*(t25.*xx + ww.*(f.*t13 - px.*t25));t63.*(t27.*xx + ww.*(f.*t18 - px.*t27));t63.*(t23.*xx - ww.*(f.*t20 + px.*t23))];

Gy = [t21.*(Xi.*t109 + Yi.*t108 - Zi.*t110 - cx.*t109 - cy.*t108 + cz.*t110);zeros(1,N);-t114.*t21;-t63.*(t118.*yy - ww.*(Xi.*t128 + Yi.*t124 + Zi.*t121 - cx.*t128 - cy.*t124 - cz.*t121));-t63.*(t132.*yy - ww.*(Xi.*t139 - Yi.*t142 + Zi.*t135 - cx.*t139 + cy.*t142 - cz.*t135));-t63.*(t146.*yy - ww.*(Xi.*t155 + Yi.*t151 + Zi.*t158 - cx.*t155 - cy.*t151 - cz.*t158));-t63.*(t25.*yy + ww.*(f.*t109 - py.*t25));t63.*(t27.*yy - ww.*(f.*t108 + py.*t27));t63.*(t23.*yy + ww.*(f.*t110 - py.*t23))];

return;


% $$$ function Derive
% $$$ 
% $$$ syms f px py wx wy wz cx cy cz;
% $$$ 
% $$$ syms Xi Yi Zi;
% $$$ syms xx yy ww;
% $$$ syms EPS;
% $$$ 
% $$$ X = [Xi; Yi; Zi; 1];
% $$$ 
% $$$ t = sqrt(wx^2+wy^2+wz^2)+EPS;
% $$$ nx = wx/t;
% $$$ ny = wy/t;
% $$$ nz = wz/t;
% $$$ N = [0 -nz ny; nz 0 -nx; -ny nx 0];
% $$$ R = eye(3) + sin(t)*N + (1-cos(t))*N*N;
% $$$ 
% $$$ C = [cx; cy; cz];
% $$$ 
% $$$ K = [f 0 px; 0 f py; 0 0 1];
% $$$ 
% $$$ P = K*R*[eye(3) -C];
% $$$ x = P*X; 
% $$$ w = x(3,:);
% $$$ y = x(2,:);
% $$$ x = x(1,:);
% $$$ 
% $$$ dxdcx = diff(x,'cx');
% $$$ dxdcy = diff(x,'cy');
% $$$ dxdcz = diff(x,'cz');
% $$$ dxdwx = diff(x,'wx');
% $$$ dxdwy = diff(x,'wy');
% $$$ dxdwz = diff(x,'wz');
% $$$ dxdf = diff(x,'f');
% $$$ dxdpx = diff(x,'px');
% $$$ dxdpy = diff(x,'py');
% $$$ 
% $$$ dydcx = diff(y,'cx');
% $$$ dydcy = diff(y,'cy');
% $$$ dydcz = diff(y,'cz');
% $$$ dydwx = diff(y,'wx');
% $$$ dydwy = diff(y,'wy');
% $$$ dydwz = diff(y,'wz');
% $$$ dydf = diff(y,'f');
% $$$ dydpx = diff(y,'px');
% $$$ dydpy = diff(y,'py');
% $$$ 
% $$$ dwdcx = diff(w,'cx');
% $$$ dwdcy = diff(w,'cy');
% $$$ dwdcz = diff(w,'cz');
% $$$ dwdwx = diff(w,'wx');
% $$$ dwdwy = diff(w,'wy');
% $$$ dwdwz = diff(w,'wz');
% $$$ dwdf = diff(w,'f');
% $$$ dwdpx = diff(w,'px');
% $$$ dwdpy = diff(w,'py');
% $$$ 
% $$$ ww2 = ww.^2;
% $$$ 
% $$$ Gx = [(ww.*dxdf-xx.*dwdf)./ww2; ...
% $$$       (ww.*dxdpx-xx.*dwdpx)./ww2; ...
% $$$       (ww.*dxdpy-xx.*dwdpy)./ww2; ...
% $$$       (ww.*dxdwx-xx.*dwdwx)./ww2; ...
% $$$       (ww.*dxdwy-xx.*dwdwy)./ww2; ...
% $$$       (ww.*dxdwz-xx.*dwdwz)./ww2; ...
% $$$       (ww.*dxdcx-xx.*dwdcx)./ww2; ...
% $$$       (ww.*dxdcy-xx.*dwdcy)./ww2; ...
% $$$       (ww.*dxdcz-xx.*dwdcz)./ww2];
% $$$ 
% $$$ Gy = [(ww.*dydf-yy.*dwdf)./ww2; ...
% $$$       (ww.*dydpx-yy.*dwdpx)./ww2; ...
% $$$       (ww.*dydpy-yy.*dwdpy)./ww2; ...
% $$$       (ww.*dydwx-yy.*dwdwx)./ww2; ...
% $$$       (ww.*dydwy-yy.*dwdwy)./ww2; ...
% $$$       (ww.*dydwz-yy.*dwdwz)./ww2; ...
% $$$       (ww.*dydcx-yy.*dwdcx)./ww2; ...
% $$$       (ww.*dydcy-yy.*dwdcy)./ww2; ...
% $$$       (ww.*dydcz-yy.*dwdcz)./ww2];
% $$$ 
% $$$ matlabFunction(Gx,Gy,'file','~/Desktop/out_derive.m');
% $$$ 
% $$$ return;
